In [2]:
import pandas as pd
from Bio import Entrez
Entrez.email = 'dmalzl@cemm.oeaw.ac.at'
Entrez.api_key = '746c80043a6e2ceeb01ae587f8ab1a8ace09'


srauid_map = pd.read_csv(
    '../metadata/archs4_accession_to_uid.tsv.gz',
    sep = '\t',
    compression = 'gzip'
)

# may contain duplicates
srauid_map.drop_duplicates(inplace = True)
srauid_map

        accession     uid database
0       SRX185895  243394      sra
1       SRX185896  243395      sra
2       SRX185897  243396      sra
3       SRX185898  243397      sra
4       SRX185899  243398      sra
...           ...     ...      ...
722660  SRX185248  242745      sra
722661  SRX185249  242746      sra
722662  SRX185250  242747      sra
722663  SRX185251  242748      sra
722664  SRX185252  242749      sra

[722425 rows x 3 columns]

In [2]:
from metadatamapping import metadata

accessions = metadata.srauids_to_accessions(srauid_map.iloc[:50134])
accessions

MainThread: 2023-11-22 12:52:37-INFO-retrieving items 0 to 50000
MainThread: 2023-11-22 12:54:14-INFO-retrieving items 50000 to 50134

,biosample,uid,database,accession_type,experiment,sample,study,bioproject,geo
0,SAMN02383463,2398516,sra,biosample,SRX1671895,SRS1369054,SRP031885,PRJNA224140,GSM1249874
1,SAMN02383461,2398517,sra,biosample,SRX1671896,SRS1369053,SRP031885,PRJNA224140,GSM1249875
2,SAMN02383456,2398518,sra,biosample,SRX1671897,SRS1369052,SRP031885,PRJNA224140,GSM1249876
3,SAMN02383457,2398519,sra,biosample,SRX1671898,SRS1369051,SRP031885,PRJNA224140,GSM1249877
4,SAMN02383460,2398520,sra,biosample,SRX1671899,SRS1369050,SRP031885,PRJNA224140,GSM1249878
...,...,...,...,...,...,...,...,...,...
50124,SAMN05171344,2569226,sra,experiment,SRX1796415,SRS1464570,SRP075613,PRJNA322604,GSM2176006
50125,SAMN05171345,2569227,sra,experiment,SRX1796416,SRS1464571,SRP075613,PRJNA322604,GSM2176007
50126,SAMN05171346,2569228,sra,experiment,SRX1796417,SRS1464572,SRP075613,PRJNA322604,GSM2176008
50127,SAMN05171347,2569229,sra,experiment,SRX1796418,SRS1464573,SRP075613,PRJNA322604,GSM2176009
50128,SAMN05171348,2569230,sra,experiment,SRX1796419,SRS1464575,SRP075613,PRJNA322604,GSM2176010

In [3]:
from metadatamapping import link
linked_uids = link.link_sra_to_biosample(accessions.uid)
linked_uids.dropna(inplace = True)
linked_uids

MainThread: 2023-11-22 12:54:20-INFO-retrieving items 0 to 1000
MainThread: 2023-11-22 12:54:40-INFO-retrieving items 1000 to 2000
MainThread: 2023-11-22 12:54:58-INFO-retrieving items 2000 to 3000
MainThread: 2023-11-22 12:55:15-INFO-retrieving items 3000 to 4000
MainThread: 2023-11-22 12:55:32-INFO-retrieving items 4000 to 5000
MainThread: 2023-11-22 12:55:51-INFO-retrieving items 5000 to 6000
MainThread: 2023-11-22 12:56:09-INFO-retrieving items 6000 to 7000
MainThread: 2023-11-22 12:56:25-INFO-retrieving items 7000 to 8000
MainThread: 2023-11-22 12:56:45-INFO-retrieving items 8000 to 9000
MainThread: 2023-11-22 12:56:59-INFO-retrieving items 9000 to 10000
MainThread: 2023-11-22 12:57:18-INFO-retrieving items 10000 to 11000
MainThread: 2023-11-22 12:57:35-INFO-retrieving items 11000 to 12000
MainThread: 2023-11-22 12:57:53-INFO-retrieving items 12000 to 13000
MainThread: 2023-11-22 12:58:10-INFO-retrieving items 13000 to 14000
MainThread: 2023-11-22 12:58:28-INFO-retrieving items 14000 to 15000
MainThread: 2023-11-22 12:58:47-INFO-retrieving items 15000 to 16000
MainThread: 2023-11-22 12:59:04-INFO-retrieving items 16000 to 17000
MainThread: 2023-11-22 12:59:21-INFO-retrieving items 17000 to 18000
MainThread: 2023-11-22 12:59:39-INFO-retrieving items 18000 to 19000
MainThread: 2023-11-22 12:59:58-INFO-retrieving items 19000 to 20000
MainThread: 2023-11-22 13:00:13-INFO-retrieving items 20000 to 21000
MainThread: 2023-11-22 13:00:30-INFO-retrieving items 21000 to 22000
MainThread: 2023-11-22 13:00:48-INFO-retrieving items 22000 to 23000
MainThread: 2023-11-22 13:01:05-INFO-retrieving items 23000 to 24000
MainThread: 2023-11-22 13:01:23-INFO-retrieving items 24000 to 25000
MainThread: 2023-11-22 13:01:40-INFO-retrieving items 25000 to 26000
MainThread: 2023-11-22 13:02:01-INFO-retrieving items 26000 to 27000
MainThread: 2023-11-22 13:02:19-INFO-retrieving items 27000 to 28000
MainThread: 2023-11-22 13:02:34-INFO-retrieving items 28000 to 29000
MainThread: 2023-11-22 13:02:52-INFO-retrieving items 29000 to 30000
MainThread: 2023-11-22 13:03:12-INFO-retrieving items 30000 to 31000
MainThread: 2023-11-22 13:03:31-INFO-retrieving items 31000 to 32000
MainThread: 2023-11-22 13:03:47-INFO-retrieving items 32000 to 33000
MainThread: 2023-11-22 13:04:05-INFO-retrieving items 33000 to 34000
MainThread: 2023-11-22 13:04:24-INFO-retrieving items 34000 to 35000
MainThread: 2023-11-22 13:04:44-INFO-retrieving items 35000 to 36000
MainThread: 2023-11-22 13:05:06-INFO-retrieving items 36000 to 37000
MainThread: 2023-11-22 13:05:25-INFO-retrieving items 37000 to 38000
MainThread: 2023-11-22 13:05:41-INFO-retrieving items 38000 to 39000
MainThread: 2023-11-22 13:05:59-INFO-retrieving items 39000 to 40000
MainThread: 2023-11-22 13:06:17-INFO-retrieving items 40000 to 41000
MainThread: 2023-11-22 13:06:35-INFO-retrieving items 41000 to 42000
MainThread: 2023-11-22 13:06:55-INFO-retrieving items 42000 to 43000
MainThread: 2023-11-22 13:07:13-INFO-retrieving items 43000 to 44000
MainThread: 2023-11-22 13:07:31-INFO-retrieving items 44000 to 45000
MainThread: 2023-11-22 13:07:46-INFO-retrieving items 45000 to 46000
MainThread: 2023-11-22 13:08:03-INFO-retrieving items 46000 to 47000
MainThread: 2023-11-22 13:08:20-INFO-retrieving items 47000 to 48000
MainThread: 2023-11-22 13:08:37-INFO-retrieving items 48000 to 49000
MainThread: 2023-11-22 13:08:56-INFO-retrieving items 49000 to 50000
MainThread: 2023-11-22 13:09:12-INFO-retrieving items 50000 to 50134

         sra biosample
0    2398516   2383463
1    2398517   2383461
2    2398518   2383456
3    2398519   2383457
4    2398520   2383460
..       ...       ...
129  2569226   5171344
130  2569227   5171345
131  2569228   5171346
132  2569229   5171347
133  2569230   5171348

[50112 rows x 2 columns]

In [7]:
biosample_metadata = metadata.biosample_uids_to_metadata(linked_uids.biosample)
biosample_metadata

MainThread: 2023-11-27 12:46:38-INFO-retrieving items 0 to 50000
MainThread: 2023-11-27 12:48:49-INFO-retrieving items 50000 to 100000
MainThread: 2023-11-27 12:50:49-INFO-retrieving items 100000 to 150000
MainThread: 2023-11-27 12:52:31-INFO-retrieving items 150000 to 200000
MainThread: 2023-11-27 12:54:55-INFO-retrieving items 200000 to 250000
MainThread: 2023-11-27 12:57:02-INFO-retrieving items 250000 to 300000
MainThread: 2023-11-27 12:58:40-INFO-retrieving items 300000 to 350000
MainThread: 2023-11-27 13:00:36-INFO-retrieving items 350000 to 400000
MainThread: 2023-11-27 13:02:23-INFO-retrieving items 400000 to 450000
MainThread: 2023-11-27 13:04:28-INFO-retrieving items 450000 to 500000
MainThread: 2023-11-27 13:06:22-INFO-retrieving items 500000 to 550000
MainThread: 2023-11-27 13:08:28-INFO-retrieving items 550000 to 600000
MainThread: 2023-11-27 13:10:27-INFO-retrieving items 600000 to 650000
MainThread: 2023-11-27 13:12:31-INFO-retrieving items 650000 to 700000
MainThread: 2023-11-27 13:14:23-INFO-retrieving items 700000 to 722243

,title,attribute,organism,biosample
0,OCI-LY1_48hrs_mRNAseq_3x_siNT_R1,source_name: Human DLBCL cel line; treatment: ...,Homo sapiens;9606,1163911
1,OCI-LY1_48hrs_mRNAseq_3x_siNT_R2,source_name: Human DLBCL cel line; treatment: ...,Homo sapiens;9606,1163912
2,OCI-LY1_48hrs_mRNAseq_3x_siNT_R3,source_name: Human DLBCL cel line; treatment: ...,Homo sapiens;9606,1163913
3,OCI-LY1_48hrs_mRNAseq_3x_siBCL6_R1,source_name: Human DLBCL cel line; treatment: ...,Homo sapiens;9606,1163914
4,OCI-LY1_48hrs_mRNAseq_3x_siBCL6_R2,source_name: Human DLBCL cel line; treatment: ...,Homo sapiens;9606,1163915
...,...,...,...,...
22217,Parkinson's Disease PD 13,source_name: Brain cortex; tissue: Human brain...,Homo sapiens;9606,1163627
22218,Parkinson's Disease PD 14,source_name: Brain cortex; tissue: Human brain...,Homo sapiens;9606,1163628
22219,Parkinson's Disease PD 15,source_name: Brain cortex; tissue: Human brain...,Homo sapiens;9606,1163629
22220,Parkinson's Disease PD 16,source_name: Brain cortex; tissue: Human brain...,Homo sapiens;9606,1163630
22221,Parkinson's Disease PD 17,source_name: Brain cortex; tissue: Human brain...,Homo sapiens;9606,1163631

In [5]:
metasra = metadata.metasra_from_study_id(accessions.study.unique())
metasra

MainThread: 2023-11-22 13:10:53-INFO-retrieving items 0 to 1000
MainThread: 2023-11-22 13:13:10-INFO-retrieving items 1000 to 1785

,study_id,study_title,sample_id,sample_name,sample_type,sample_type_confidence,mapped_ontology_ids,mapped_ontology_terms,raw_SRA_metadata,sample_species,assay
0,SRP031885,Brd4 and JMJD6-associated Anti-pause Enhancers...,SRS1369056,HEK293T cell,cell line,1.0,"CL:0000010, CVCL:0045, EFO:0001182, EFO:000072...","cultured cell, HEK293, transfection, kidney",cell line: Human Embryonic Kidney 293 cells; s...,human,RNA-seq
1,SRP031885,Brd4 and JMJD6-associated Anti-pause Enhancers...,SRS1369051,HEK293T cell,cell line,1.0,"CL:0000010, CVCL:0045, EFO:0001182, EFO:000072...","cultured cell, HEK293, transfection, kidney",cell line: Human Embryonic Kidney 293 cells; s...,human,RNA-seq
2,SRP031885,Brd4 and JMJD6-associated Anti-pause Enhancers...,SRS1369055,HEK293T cell,cell line,1.0,"CL:0000010, CVCL:0045, EFO:0001182, EFO:000072...","cultured cell, HEK293, transfection, kidney",cell line: Human Embryonic Kidney 293 cells; s...,human,RNA-seq
3,SRP031885,Brd4 and JMJD6-associated Anti-pause Enhancers...,SRS1369050,HEK293T cell,cell line,1.0,"CL:0000010, CVCL:0045, EFO:0001182, EFO:000072...","cultured cell, HEK293, transfection, kidney",cell line: Human Embryonic Kidney 293 cells; s...,human,RNA-seq
4,SRP031885,Brd4 and JMJD6-associated Anti-pause Enhancers...,SRS1369059,HEK293T cell,cell line,1.0,"CL:0000010, CVCL:0045, EFO:0001182, EFO:000072...","cultured cell, HEK293, transfection, kidney",cell line: Human Embryonic Kidney 293 cells; s...,human,RNA-seq
...,...,...,...,...,...,...,...,...,...,...,...
309,SRP075613,Next generation sequencing of esophageal squam...,SRS1464769,Esophageal squamous cell carcinoma,cell line,1.0,"CL:0000010, EFO:0005922, EFO:0006628, CVCL:134...","cultured cell, esophageal squamous cell carcin...",cell line: Esophageal squamous cell carcinoma ...,human,RNA-seq
310,SRP075613,Next generation sequencing of esophageal squam...,SRS1464767,Esophageal squamous cell carcinoma,cell line,1.0,"CL:0000010, EFO:0005922, EFO:0006628, CVCL:134...","cultured cell, esophageal squamous cell carcin...",cell line: Esophageal squamous cell carcinoma ...,human,RNA-seq
311,SRP075613,Next generation sequencing of esophageal squam...,SRS1464793,Esophageal squamous cell carcinoma,cell line,1.0,"CL:0000010, EFO:0005922, EFO:0006628, CVCL:134...","cultured cell, esophageal squamous cell carcin...",cell line: Esophageal squamous cell carcinoma ...,human,RNA-seq
312,SRP075613,Next generation sequencing of esophageal squam...,SRS1464785,Esophageal squamous cell carcinoma,cell line,1.0,"CL:0000010, EFO:0005922, EFO:0006628, CVCL:134...","cultured cell, esophageal squamous cell carcin...",cell line: Esophageal squamous cell carcinoma ...,human,RNA-seq
313,SRP075613,Next generation sequencing of esophageal squam...,SRS1464736,Esophageal squamous cell carcinoma,cell line,1.0,"CL:0000010, EFO:0005922, EFO:0006628, CVCL:134...","cultured cell, esophageal squamous cell carcin...",cell line: Esophageal squamous cell carcinoma ...,human,RNA-seq